
import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfServicePage: React.FC = () => {
  const lastUpdated = "October 26, 2023"; // Example date

  return (
    <div className="bg-white shadow-lg rounded-xl p-6 sm:p-8 lg:p-10 max-w-4xl mx-auto my-8 text-gray-700 leading-relaxed">
      <header className="text-center mb-10">
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-800 mb-3">
          Terms of Service
        </h1>
        <p className="text-md text-gray-500">Last Updated: {lastUpdated}</p>
      </header>

      <p className="mb-6">
        Welcome to AI CV Maker! These Terms of Service ("Terms") govern your use of our website, applications, and services, including our AI-powered CV generation tools (collectively, the "Services"). By accessing or using our Services, you agree to be bound by these Terms and our <Link to="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</Link>. If you do not agree to these Terms, do not use our Services.
      </p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">1. Use of Services</h2>
        <ul className="list-disc list-inside space-y-2 pl-4 mb-3">
          <li>
            <strong>Eligibility:</strong> You must be at least 16 years old (or the age of legal majority in your jurisdiction) to use our Services.
          </li>
          <li>
            <strong>Account Registration:</strong> You may need to register for an account to access certain features. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. You are responsible for safeguarding your account password and for all activities that occur under your account.
          </li>
          <li>
            <strong>Acceptable Use:</strong> You agree not to use the Services for any unlawful purpose or in any way that interrupts, damages, or impairs the service. You will not attempt to gain unauthorized access to our systems or engage in any activity that disrupts the Services for other users.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">2. CV Content and AI Generation</h2>
        <ul className="list-disc list-inside space-y-2 pl-4 mb-3">
          <li>
            <strong>User Responsibility:</strong> You are solely responsible for the accuracy, legality, and completeness of the information you provide for CV generation. AI CV Maker is a tool to assist you; the final CV content is your responsibility to review and verify.
          </li>
          <li>
            <strong>AI Output:</strong> The CVs generated by our AI are based on the information you provide and the patterns learned by the AI model. While we strive for high-quality output, we do not guarantee that the generated CV will secure you an interview or employment. The AI may sometimes produce inaccurate or incomplete information.
          </li>
          <li>
            <strong>No Professional Advice:</strong> The Services provide AI-generated suggestions and outlines. This does not constitute professional career advice, HR consulting, or legal advice.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">3. Intellectual Property</h2>
        <ul className="list-disc list-inside space-y-2 pl-4 mb-3">
          <li>
            <strong>Our IP:</strong> The Services, including our website, software, design, text, graphics, and the AI models (excluding the user-provided data fed into them for specific generation tasks and the resulting user-specific output), are the property of AI CV Maker or its licensors and are protected by intellectual property laws.
          </li>
          <li>
            <strong>Your Content:</strong> You retain all ownership rights to the personal information and raw content you submit to the Services. By using the Services, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and transmit your content solely for the purpose of providing and improving the Services, including training our AI models (typically on an anonymized or aggregated basis, as detailed in our Privacy Policy).
          </li>
          <li>
            <strong>Generated CVs:</strong> You own the specific CV document generated for you based on your input. However, the underlying templates, AI-generated phrases (if generic), and structure provided by the Service remain our intellectual property or that of our licensors.
          </li>
        </ul>
      </section>
      
      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">4. Fees and Payment (If Applicable)</h2>
        <p className="mb-3">
          Currently, basic access to AI CV Maker may be free. We reserve the right to introduce fees for certain features or subscription plans in the future. Any such changes will be communicated to you in advance, and your continued use of fee-based services will require your agreement to the payment terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">5. Disclaimers</h2>
        <p className="mb-3">
          THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. AI CV MAKER DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">6. Limitation of Liability</h2>
        <p className="mb-3">
          TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, AI CV MAKER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">7. Indemnification</h2>
        <p className="mb-3">
          You agree to indemnify and hold harmless AI CV Maker and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your access to or use of the Services or your violation of these Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">8. Termination</h2>
        <p className="mb-3">
          We may terminate or suspend your access to our Services immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Services will immediately cease.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">9. Governing Law</h2>
        <p className="mb-3">
          These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction - e.g., State of California, USA], without regard to its conflict of law provisions.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">10. Changes to Terms</h2>
        <p className="mb-3">
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Services after any revisions become effective, you agree to be bound by the revised terms.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-800 mb-2">11. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us through our <Link to="/contact-us" className="text-blue-600 hover:underline">Contact Us</Link> page or at <a href="mailto:legal@aicvmaker.com" className="text-blue-600 hover:underline">legal@aicvmaker.com</a>.
        </p>
      </section>
    </div>
  );
};

export default TermsOfServicePage;